name: Dependency Review

on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        
      - name: Python Security Dependencies Check
        uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          inputs: requirements.txt 